### ISSUE TITLE
Too few arguments to function Cosmic\App\Controllers\Home\Index::index(), 1 passed

### ISSUE THREAD

**Issue by raizdev** [sunrise-php/http-router#105]
Trying to make a controller but I dont get it work with the responseInterfaces
Receiving Too few arguments to function Cosmic\App\Controllers\Home\Index::index(), 1 passed

`
namespace Cosmic\App\Controllers\Home;

use Sunrise\Http\Router\Annotation as Mapping;
use Psr\Http\Message\ServerRequestInterface as Request;
use Psr\Http\Message\ResponseInterface as Response;

class Index {
  
    #[Mapping\Route('/', path: '/')]
    public function index(Request $request, Response $response) {
        echo 1;
    }
}
`

**Comment by fenric** [comment]
Hi, @raizdev! You need PSR-(1)7 implementation...

```php
declare(strict_types=1);

namespace Cosmic\App\Controllers\Home;

use Sunrise\Http\Router\Annotation as Mapping;
use Psr\Http\Message\ServerRequestInterface as Request;
use Psr\Http\Message\ResponseInterface as Response;

class Index
{
    #[Mapping\Route('index', path: '/')]
    public function index(Request $request): Response
    {
        return (new ResponseFactory)->createResponse(200);
    }
}
```

**Comment by raizdev** [comment]
> Hi, @raizdev! You need PSR-(1)7 implementation...
> 
> ```
> declare(strict_types=1);
> 
> namespace Cosmic\App\Controllers\Home;
> 
> use Sunrise\Http\Router\Annotation as Mapping;
> use Psr\Http\Message\ServerRequestInterface as Request;
> use Psr\Http\Message\ResponseInterface as Response;
> 
> class Index
> {
>     #[Mapping\Route('index', path: '/')]
>     public function index(Request $request): Response
>     {
>         return (new ResponseFactory)->createResponse(200);
>     }
> }
> ```

Thank you for your explantation!

I was wondering if it is possible to add ResponseFactory in a container to get them through the function. Using  (new ResponseFactory)-> feels codingwise not correct
