### ISSUE TITLE
Hard dependence on ResponseFactory

### ISSUE THREAD

**Issue by PhantomArt** [sunrise-php/http-router#23]
`RequestHandler` uses `Sunrise\Http\Message\ResponseFactory`. How about adding `Psr\Http\Message\RequestFactoryInterface` dependencies to the constructor of `RequestHandler` and  `Router` classes?

**Comment by fenric** [comment]
Hello @PhantomArt! Thanks for your question!

I thought about it. I'm preparing release v1.1.0. I think it will be added there. I don't know yet how it will be implemented, but I think something like this:

```php
$router = new Router(new ResponseFactory());

// some code...
```

I also think to make annotation support out of the box. What do you think about it?

**Comment by PhantomArt** [comment]
Я могу говорить по-русски?

Я прочитал вашу статью на хабрахабре. Я настороженно отношусь к аннотациям, поэтому не уверен, что данный функционал будет для меня востребован. Но я вижу ещё пару вещей, над которыми нужно поработать:

1. На данный момент невозможно добавить Middleware к `RouteCollection`. Насколько я могу судить, это реализовать довольно легко. Необходимость в таком решении очевидна: например, я хочу выделить группу правил для реализации API и повесить на неё некоторые особенные Middleware. Даже ваш пример с `DemoMiddleware` выглядит избыточным, потому что `DemoMiddleware` добавляется к каждому правилу отдельно внутри группы.

2.  Ваш роутер реализует `RequestHandlerInterface`. То есть он выступает в роли обработчика запросов, в отличие от других реализаций, когда роутер является Middleware. Это приводит к негативному эффекту.

Роутеру приходится бросить такие исключения, как `MethodNotAllowedException` и `RouteNotFoundException`. Где я должен их перехватывать? Неужели напрямую в фронт-контроллере? Или я должен создать ещё один хэндлер-враппер, который будет этим заниматься?

Если бы вы использовали парадигму, когда роутер является Middleware, то его можно было бы вставить в цепочку, где самым первым был бы `Middlewares\ErrorHandler`, который перехватывает любые исключения.

Это можно решить, если написать враппер над роутером, который будет реализовывать `MiddlewareInterface`, но мне кажется, будет гораздо лучше, если сам роутер будет реализовывать `MiddlewareInterface`.

Если я вас ещё не убедил, то в стандарте PSR15 есть рекомендация по этому поводу: https://www.php-fig.org/psr/psr-15/

> 1.4 Handling Exceptions
It is RECOMMENDED that any application using middleware includes a component that catches exceptions and converts them into responses. This middleware SHOULD be the first component executed and wrap all further processing to ensure that a response is always generated.


Я обратил на вашу работу внимание благодаря заявлению о том, что ваш роутер работает быстрее, чем FastRoute. Мне понравился строгий и чистый код, но вышеописанные недостатки делают его неудобным для использования.

**Comment by fenric** [comment]
Приветствую @PhantomArt !

Я попробую реализовать к ближайшему выпуску возможность привязки промежуточного ПО к коллекции маршрутов. Я думал об этом ранее, но в силу того, что я использую преимущественно аннотации, не брался за это. Спрос рождает реализацию :)

---

По поводу бросаемых исключений из маршрутизатора и как с ними работать. Я не могу навязывать вам реализацию обозначенного, однако с радостью поделюсь своим опытом. Как правило, мои проекты выглядят примерно следующим образом:

1. Точка входа `public/index.php` или `worker.php` (зависит от реализации запуска):

```php
declare(strict_types=1);

use App\Http\Application;

require __DIR__ . '/vendor/autoload.php';

$application = new Application();

$application->run();
```

2. Экземпляр приложения:

```php
declare(strict_types=1);

namespace App\Http;

class Application
{
    public function run() : void
    {
        $router = new Router();

        try {
            $response = $router->handle(...);
        } catch ($e) {
            // some code
        }
    }
}
```

Конечно, на самом деле все сложнее, маршрутизатор в регистре, регистр в контейнере, контейнер в ядре, ядро наследуется приложением, а логика обработки ошибок вынесена в сервис...

---

Вы заставили меня серьезно задуматься, в первую очередь, из-за условно называемого `ErrorHandleMiddleware`... Скорей всего, я начну готовить релиз `v2.0.0`, где я пересмотрю логику запуска маршрутизатора...

---

Пользуясь случаем, был бы рад услышать ваше мнение, касаемо следующего: в данный момент, я думаю над тем, как `controller` / `middleware` должен получать доступ к контейнеру (PSR-11). Есть идея, добавить маршрутизатору возможность хранить контейнер в себе, после чего передавать его маршруту, который передаст его всем своим `middlewares`... Как-то там, конечно можно, в разных микросервисах у меня крутится как минимум 2 решения этой проблемы, первая это `Injection` благодаря аннотациям, вторая это `ContainerAwareTrait`... Но оба эти варианты кажутся не верными.

---

В любом случае, большое спасибо, это был крайне полезный `issue`!

**Comment by PhantomArt** [comment]
Я наконец-то нашёл время, чтобы дать развёрнутый ответ.

В чём проблема
--------------

Предположим, я хочу выводить пользователю какую-то особую страницу, когда маршрут не найден (404 Not Found). Логично, что я хочу, чтобы у меня был контроллер, который будет получать управление, когда такая ситуация происходит. При вашем подходе, мне придётся добавлять вызов этого контроллера внутри секции `catch` в методе `Application::run`.

Но это неправильно. `Application` вообще не должен ничего знать о контроллерах и что они из себя представляют. Это могут быть отдельные классы на каждое действие, или набор методов классов по одному на каждое действие, или функции-замыкания - это всё находится вне его зоны ответственности.

О стандарте PSR15
-----------------

Стандарт PSR15 говорит нам, что мы должны реализовать `RequestHandlerInterface` с методом `handle`. Этот метод должен получить в качестве аргумента `ServerRequestInterface` и вернуть `ResponseInterface`. Я считаю, что нужно стремиться, чтобы метод `handle` не выбрасывал собственных исключений, хотя в стандарте и написано, что обработчик запросов может выбрасывать исключения.

Но откуда метод `handle` должен взять требуемый от него `Response`? В некоторых реализациях может потребоваться, чтобы он сам его сгенерировал, к примеру, если у нас есть класс-контроллер, который реализует интерфейс `RequestHandlerInterface`. Но в случае, когда мы хотим, чтобы `RequestHandler` под капотом работал с `Middleware`, он в своих зависимостях даже `ResponseFactory` может не иметь. Все `Response` он будет получать от цепочки `Middleware`. А вот `Middleware` в свою очередь уже могут иметь в зависимостях `ResponseFactory`.

Кстати сказать, если `RequestHandler` не имеет возможности сам создавать `Response` и во всём полагается на `Middleware`, то тогда в одном случае всё таки придётся бросать исключение из метода `handle`: если программист не задал ни одного `Middleware`, то тогда `RequestHandler` в принципе не сможет обработать запрос и выдать ответ.

Эту ситуацию можно обрабатывать по-разному. Например, в библиотеке [relay/relay](https://github.com/relayphp/Relay.Relay), судя по исходному коду будет `Fatal error`. Разработчик вообще решил никак эту ситуацию не обрабатывать. И возможно он правильно делает. Потому что это ошибка программиста, который неправильно сконфигуровал `RequestHandler`. С другой стороны, конкретно в `relay/relay` все `Middleware` передаются в виде массива в конструктор. Можно было бы проверять в конструкторе, пуст массив или нет, и если пуст, то выбрасывать исключение ещё на этапе конструирования объекта. Может даже стоит ему об этом написать.
 
Тогда возникает вопрос: если `RequestHandler` полностью зависит от `Middleware`, которые могут быть написаны разными программистами, то где гарантии, что исключение не возникнет в одном из них? В стандарте не написано, может ли `Middleware` выбрасывать исключения, но там есть пункт, о котором я говорил в прошлом сообщении, процитирую его ещё раз:

> 1.4 Handling Exceptions
It is RECOMMENDED that any application using middleware includes a component that catches exceptions and converts them into responses. This middleware SHOULD be the first component executed and wrap all further processing to ensure that a response is always generated.

Например, [middlewares/error-handler](https://github.com/middlewares/error-handler) именно это и делает. Это `Middleware` позволяет делегировать логику обработки ошибок при помощи форматтеров. В состав библиотеки уже входит набор различных форматтеров, но можно создавать и свои.

Роутер в контексте PSR15
------------------------

Идея PSR15 в том, что `RequestHandlerInterface` может опираться на `MiddlewareInterface`, а `MiddlewareInterface` может опираться на `RequestHandlerInterface`. Во главе всего находится некий `RequestHandler`, который делегирует обработку запроса цепочке `Middleware`. Большая часть `Middleware` не будет генерировать `Response`, а будет получать его от следующего `Middleware` в цепочке. Но где-то в конце цепочки найдётся `Middleware`, которому придётся сгенерировать ответ. Такое `Middleware` может создать его на основе фабрики или делегировать создание кому-то ещё, к примеру ещё одному `RequestHandler`, который в свою очередь тоже может иметь под капотом свои `Middleware`!

Допустим в фреймворке Laravel `Middleware` можно вешать как гирлянду куда угодно: на отдельные маршруты, на группы маршрутов, и даже на отдельные методы контроллеров! Не достаточно хорошо знаком с другими фреймворками, но наверно и в них дело обстоит так же.

В контексте всего вышесказанного, я склонен считать, что `RequestHandler`, находящийся в самом начале всей этой матрёшки, должен быть просто тонкой обёрткой вокруг группы `Middleware`. С этим хорошо справляется `relay/relay`. Роутер тоже может являться `RequestHandler`, но в большинстве случаев использования он будет встраиваться в качестве `Middleware`, а значит нужен класс-обёртка, реализующая интерфейс `MiddlewareInterface`.

И кстати ничто не мешает сделать роутер, который реализует сразу оба интерфейса: `RequestHandlerInterface` и `MiddlewareInterface`.

Вот пример `Middleware` для использования `FastRoute`: [middlewares/fast-route](https://github.com/middlewares/fast-route). А вот `Aura.Router`: [middlewares/aura-router](https://github.com/middlewares/aura-router). Эти роутеры сами по себе не поддерживают стандарт PSR15, поэтому пришлось делать для них обёртки в виде `Middleware`. Но заметьте, обёртки сделаны именно в виде `Middleware`, а не `RequestHandler`!

Роутер и контроллеры
--------------------

Должна ли библиотека роутинга навязывать формат контроллеров? А так ли это необходимо?

Если взглянуть на `middlewares/fast-route` и `middlewares/aura-router`, то выяснится, что они лишь находят нужный маршрут и записывают ассоциированное с ним значение в специальный атрибут запроса. Имя атрибута по умолчанию `request-handler`, но его можно задать произвольным.

Таким образом роутеру ничего не нужно знать про контроллеры. Можно даже заменить один роутер на другой! Конечно, роутеры инициализируются по-разному, маршруты назначаются тоже по-разному, но тем не менее, нигде в кишках системы ничего менять не придётся.

Возникает вопрос: если роутер не вызывает контроллеры, то кто это делает?

Всё просто: ещё одно `Middleware`, которое программист должен задать где-то дальше в цепочке. Оно может идти сразу после роутера, но не обязательно. Вполне возможно, что между определением маршрута и вызовом контроллера будут стоять ещё какие-то `Middleware`.

Вот пример такого `Middleware`: [middlewares/request-handler](https://github.com/middlewares/request-handler). Если посмотреть исходный код, то оно довольно всеядное. Что бы роутер ни пихал в атрибут `request-handler`, оно будет пытаться его интерпретировать:

Строка? Значит нужно попытаться найти контроллер в `ContainerInterface` контейнере.
Массив из двух элементов? Значит это объект с методом.
А если в этом массиве нулевой элемент строка, а не объект? Значит это имя класса и опять же ищем его в контейнере.
`MiddlewareInterface`? Ок, значит вызываем метод `process`.
`RequestHandlerInterface`? Вызываем метод `handle`.
Ничего из перечисленного, но зато является `callable`? Значит вызываем непосредственно!

Ну а уж если не получается интерпретировать никак, то кидаем исключение.

И опять же ничто не мешает реализовать своё подобное `Middleware`, если `middlewares/request-handler` не удовлетворяет потребностям. Допустим, если я хочу обвешивать методы контроллеров дополнительными `Middleware`, то возможно мне придётся сделать своё `Middleware`, которое читает атрибут `request-handler` и выполняет необходимые действия.

Я думаю, это отвечает и на ваш вопрос, как именно `Middleware` должно получать доступ к контейнеру. Просто передайте его в конструктор только тому `Middleware`, которое в нём нуждается. Возможно, я сделал бы отдельный контейнер для контроллеров, чтобы это больше было похоже на фабрику контроллеров, а не на сервис локатор.

Постскриптум
------------

Я сейчас пытаюсь сделать свой велосипед, основанный на практиках, описанных в PSR. Ваш роутер немного напомнил мне роутер в Laravel. У меня была идея выдрать роутер из Laravel, но уж слишком много зависимостей он за собой тянет, да ещё и не совместимых с PSR. Многие компоненты Laravel вынимаются легко и непринуждённо, роутер не в их числе.

Извиняюсь за много букв.

**Comment by PhantomArt** [comment]
Позвольте, я ещё добавлю немного слов.

Рассматриваю сейчас компонент [league/route](https://github.com/thephpleague/route), он в чём-то похож на вашу разработку, но в нём решены описанные мной проблемы. Правда, там нет поддержки аннотаций.

Они используют похожую парадигму, когда роутер находится во главе всего и является коренным обработчиком запросов. Почему-то они не реализуют интерфейс `RequestHandlerInterface`, я уже создал об этом issue. В остальном, там присутствует хорошая поддержка PSR стандартов.

Они решили проблему выбрасываемых исключений при помощи так называемых [стратегий](https://route.thephpleague.com/4.x/strategies/). Они поддерживают вызов контроллеров из коробки. Причём возвращаемое значение из контроллеров зависит от стратегии. Например, если используется `JsonStrategy`, то из контроллеров можно возвращать не только `ResponseInterface`, но и массив или объект. Это очень удобная фича, потому что во многих случаях возвращать `ResponseInterface` из контроллеров несколько утомительно.

У них присутствуют группы маршрутов. На каждый маршрут или группу можно повесить свои middleware и задать стратегию. Помимо этого маршрут характеризуется не только методом запроса и путём, но также протоколом, хостом и портом. Я сейчас рефакторю проект, где используются поддомены для различных стран, возможно, мне эта фича пригодится. 

Я думаю, вам стоит взглянуть на эту разработку, если вы планируете придерживаться парадигмы роутера как центрального узла.

Я уже использовал некоторые компоненты от [thephpleague](https://thephpleague.com/), например: Container, Flysystem, Plates - впечатления положительные.

**Comment by fenric** [comment]
@PhantomArt 

> Извиняюсь за много букв.

Отнюдь, я вам искренне благодарен за проявленный интерес! Я сторонник простых и изящных решений, в силу своих возможностей разумеется. Как мне кажется, я нашел хорошее решение, которое на данный момент я реализую.

Маршрутизатор теперь будет сам по себе промежуточным ПО, действительно у такого подхода больше плюсов, чем минусов, ниже пример:

```php
// routes collection
$routes = new RouteCollection();

// home route
$routes->get('home', '/')
->addMiddleware(new HomeFirstMiddleware())
->addMiddleware(new HomeSecondMiddleware());

// news route
$routes->get('news', '/news')
->addMiddleware(new NewsFirstMiddleware())
->addMiddleware(new NewsSecondMiddleware());

// creating a new router instance with created routes
// * I'm think about this...
$router = (new Router)->addRoutes($routes);

// it's test request handler
$handler = new RequestHandler(new class implements RequestHandlerInterface {
    public function handle(ServerRequestInterface $request) : ResponseInterface {
        return (new ResponseFactory)->createResponse();
    }
});

// adding middlewares to the handler
$handler->add(new ErrorHandleMiddleware());
$handler->add(new FirstMiddleware());
$handler->add(new SecondMiddleware());
$handler->add($router);
$handler->add(new PenultimateMiddleware());
$handler->add(new LastMiddleware());

// handling the request
respond($handler->handle(ServerRequestFactory::fromGlobals()));
```

Для запуска маршрутизатора, получается, что всегда нужен будет некий `RequestHandler`, именно ему он делегирует обработку запроса после того, как выполнит свою часть работы. Следом пропала необходимость тянуть за собой `Sunrise HTTP Message` PSR-7 библиотеку, так как вместо того, чтобы создать чистый `Response`, маршрутизатор просто делегирует эту ответственность на родительский `RequestHandler`. По сути это решит первоначальную проблему, о которой вы изначально заговорили. И конечно-же, сам маршрутизатор больше не будет выступать в качестве `RequestHandler`, из коробки будет все, для корректного его запуска.

Я думаю, что `Router` больше не должен аккумулировать промежуточное ПО, так как логика работы с ним сильно меняется. За то, этим станет заниматься коллекция маршрутов, это то, о чем вы говорили также:

```php
$routes->addMiddleware(...);
$routes->addMiddleware(...);
$routes->addMiddleware(...);
$route = $routes->get('home', '/');
```

```php
$routes->group('/v1', function ($routes) {
  $routes->addMiddleware(...);
  $routes->addMiddleware(...);
  $routes->addMiddleware(...);
  $route = $routes->get('entity', '/{id}');
});
```

Ну и последнее, о чем я думаю, это о том, стоит ли вообще, бросать исключения, или быть может, стоит завести классы `Matcher` and `MatchResult`, и ловить уже класс `MatchResult` где-то в `Middleware`, по типу следующего:

```php
$routeMatchResult = $request->getAttribute('@routeMatchResult');

if ($routeMatchResult->isSuccess()) {
  // continue
}

// breaking...
```

Так или иначе, с большим удовольствием выслушал бы вас касаемо всего вышеизложенного!

**Comment by fenric** [comment]
@PhantomArt по поводу вышеобозначенного маршрутизатора... Вместо стратегий мы используем другой подход, к примеру:

```php
return $this->ok($response, [
  'items' => ...,
], 200);
```

```php
return $this->error($response, 'description', 500);
```

```php
return $this->violations($response, $violations, 400);
```

Просто имея некий `AbstractMiddleware` или `ResponderInjection`. Намного проще будет сменить стек, в случае такой необходимости, чем писать новую обертку для всего промежуточного ПО, и повторять логику обработки данных прошлого маршрутизатора... Плюс, вернув не `Response`, это уже не `Middleware` получается...

Как ранее было написано, я сторонник простых и эффективных решений, чем проще решение, тем его проще поддерживать, и снижается риск каких-то сюрпризов... Хороший код – код которого нет. Если без этого можно обойтись – оно не нужно. Это сложный баланс, между простотой и удобством использования такого ПО...

**Comment by PhantomArt** [comment]
Корневой `RequestHandler` не должен нести ответственность за создание `Response`.

Когда запрос продвигается по цепочке `Middleware`, то любое из них может сказать "стоп!", сгенерировать `Response` и вернуть его, не вызывая следующее `Middleware` в цепочке.

Некоторые `Middleware` в принципе не предназначены, чтобы генерировать ответ, например, они просто могут модифицировать некоторые HTTP заголовки запроса или ответа.

Но есть и другие виды `Middleware`. Очень хорошо это можно показать на примере [middlewares/cache](https://github.com/middlewares/cache). Оно проверяет, есть ли для текущего запроса валидное значение ответа в кэше, и если есть, то немедленно возвращает его, таким образом запрос даже не доходит до вызова контроллера. Но если значения в кэше нет, то тогда оно передаёт управление следуюшему `Middleware` в цепочке, после чего кэширует возвращённый `Response`.

Из этого следует, что любое `Middleware`, функционал которого предусматривает создание `Response`, должен в зависимостях иметь `ResponseFactoryInterface`. Некоторые из них могут иметь в своём составе собственную фабрику, но в таком случае всё равно нужно давать пользователю возможность задать свою. Например, вышеописанное `middlewares/cache` делает так:

```
use Middlewares\Utils\Factory;

// ...

public function __construct(CacheItemPoolInterface $cache, ResponseFactoryInterface $responseFactory = null)
{
    $this->cache = $cache;
    $this->responseFactory = $responseFactory ?: Factory::getResponseFactory();
}
```

Возможность задать свою фабрику имеется, но в то же время у ленивых разработчиков будет работать и без этого. Но я не люблю поддерживать ленивых разработчиков. Я бы сделал требование фабрики обязательным. 

Возможно, они даже оказывают медвежью услугу, потому что скорее всего в некоторых библиотеках, предназначенных для управления зависимостями, придётся вручную указывать, что фабрику туда нужно передать. Иначе как библиотека поймёт нужно передавать туда фабрику или нет, если у параметра имеется значение по умолчанию? Возможно, я преувеличиваю проблему, потому что у меня мало опыта в этом, я не так давно начал использовать что-то сложнее `Pimple`, в котором все зависимости задаются вручную.

> Ну и последнее, о чем я думаю, это о том, стоит ли вообще, бросать исключения, или быть может, стоит завести классы Matcher and MatchResult, и ловить уже класс MatchResult где-то в Middleware, по типу следующего:

Отсутствие атрибута 'request-handler' можно рассматривать как отсутствие найденного маршрута. Но помимо этой ситуации может ещё возникнуть `MethodNotAllowedException`. Как я выше написал, `Middleware` вправе остановить выполнение запроса на своём уровне и само сгенерировать `Response`. Но в данном случае разработчик может хотеть иметь возможность перехватывать эти ситуации при помощи специальных контроллеров.

Не могу сходу придумать, как красиво решить эту проблему. Может сделать у роутера возможность задавать спец. маршруты для этих ситуаций? Вот так:

```
$router->notFound('not_found');
$router->methodNotAllowed('method_not_allowed');

```

Или вот так:

```
$router->special(Router::NOT_FOUND, 'not_found');
$router->special(Router::METHOD_NOT_ALLOWED, 'method_not_allowed');
```

Тогда возможно стоит сделать так, чтобы класс `Router` расширял класс `RouteCollection`. В таком случае `Router` будет являться коренной коллекцией. Вроде бы ничего от этого не пострадает, даже на один объект меньше придётся создавать.

В `league/route` есть набор исключений для 4xx кодов HTTP, которые можно бросать прямо из контроллеров. И они преобразуются в нужный `Response` в зависимости от стратегии. Например, в `JsonStrategy` это будет JSON. Впрочем, я пока не совсем понимаю, как научить стратегию генерировать в таком случае какой-то презентабельный `Response` в виде HTML страницы, сгенерированной шаблонизатором. Я ещё не вникал так глубоко. Но в любом случае никто не заставляет бросать исключения, можно сгенерировать `Response` в контроллере.

На данный момент я хочу попробовать внедрить `league/route` в текущий проект, потому что он имеет очень много полезных мне возможностей.

Какие виды контроллеров вы планируете поддерживать в реализации своего обработчика (последнего `Middleware` в цепочке)? То есть как будет выглядеть типичный контроллер в реальном проекте?

Кстати, очень многие разработчики роутеров молча обходят стороной ещё одну полезную возможность: генерация URL на основе маршрутов. То есть это обратная функция поиску маршрутов, когда мы знаем имя маршрута и набор параметров, и хотим получить соответствующий путь. Эта функция должна тесно сотрудничать с компонентом роутинга, её не получится реализовать независимо от конкретного роутера. Тоже неплохая такая киллер фича.

**Comment by fenric** [comment]
И вот, спустя 3 месяца, почти готов релиз 2.0, в котором многое было реализовано и переделано...

https://github.com/sunrise-php/http-router/tree/release/v2.0.0

**Comment by PhantomArt** [comment]
Здорово! Обязательно посмотрю, когда возникнет необходимость. На данный момент работаю над проектами в несколько другой плоскости.

**Comment by fenric** [comment]
В принципе, все выше-обозначенное решено в версии 2.0.
