### ISSUE TITLE
Add support for group middleware

### ISSUE THREAD

**Issue by rask** [sunrise-php/http-router#25]
I would love to be able to do something similar to the following:

```php
$router->group('/api', function ($group) {
    $group->get('api-home', '/')->addMiddleware(new ApiHomeAction());
}, [new MyApiMiddleware()]);
```

After which all routes that were defined inside the group receive the middleware definition.

I can probably subclass the route collector to accept the third parameter, but would this be a large enough of a usecase to be implemented into the package itself?

**Comment by fenric** [comment]
Hello!

I prepare the version 2.0.0. The release is expected this week.

The new version contains a solution to your problem:

```php
$routes->group('/admin', function ($group) {
    $group->addMiddleware(new AdminAuthenticationMiddleware());
    $group->addMiddleware(new AdminAuthorizationMiddleware());

    // some code...
});
```

Also, the new version contains a solution to your other problem:

```php
$routes->group('/', function ($group) {
    // will be the following path: /
    $group->get('home', '/', new HomeRequestHandler());
});
```

The new version will have a lot of new :)

**Comment by rask** [comment]
Good to hear, will wait for 2.0 to implement these things in that case. Thanks!
