### ISSUE TITLE
Add support for a bare group path

### ISSUE THREAD

**Issue by rask** [sunrise-php/http-router#26]
When I use the following:

```php
$routes->group('/', function ($group) {
    $group->get('index', '/');
});
```

The resulting route will match `//`, not `/`.

I tried, and removing the `/` from either the `group` call, or the `get` call makes it work again, but for the sake of usability I would like to see the generated route collapse multiple `/` into a single `/`.

**Comment by fenric** [comment]
Hello! I answered to you here #25

**Comment by rask** [comment]
Hi, answer is satisfactory, thanks!
