### ISSUE TITLE
Route name support

### ISSUE THREAD

**Issue by dominikzogg** [sunrise-php/http-router#28]
I am interested to add your router to my framework: https://github.com/chubbyphp/chubbyphp-framework

This would need route name support and https://github.com/sunrise-php/http-router/issues/27 and the following would be cool to: https://github.com/sunrise-php/http-router/issues/23

**Comment by fenric** [comment]
Hello! Now, I write tests for the 2.0.0 release. The new release contains the following features:

1. Route's endpoint it's RequestHandler;
2. Each route it's RequestHandler;
3. Each route also supports middlewares;
4. Collection for routes also supports middlewares;
5. Router it's collection;
6. Router it's middleware;
7. Router doesn't throw exceptions;
8. #23 completed;
9. #25 completed.

* #27 will realized in 2.0.*, very soon.

Router work example: 

```php
$router = new Router();
$router->get('home', '/', new HomeRequestHandler());

$handler = new QueueableRequestHandler(new DefaultRequestHandler());
$handler->add(new ErrorHandleMiddleware());
$handler->add($router);

$handler->handle(...);
```

Callback support:

```php
$router->get('home', '/', new CallableRequestHandler(function ($req, $res) {
    // some code...
}));
```

Redirect support from RequestHandler:

```php
public function handle(ServerRequestInterface $request) : ResponseInterface
{
    return $this->getRouter()->getRoute('login')->handle($request);
}
```

Collection's middleware support:

```php
$router->group('/admin', function ($group) {
    $group->addMiddlewares(
        new FooMiddleware(),
        new BarMiddleware(),
        new BazMiddleware(),
    );

    // or...
    $group->addMiddlewares(...[
        new FooMiddleware(),
        new BarMiddleware(),
        new BazMiddleware(),
    ]);
});
```

Collections merge support:

```php
$a = new RouteCollection();
// some code...

$b = new RouteCollection();
// some code...

$router->merge($a, $b);
```

Route patterns:

```php
$router->get('post.read', '/v1/post/{id<\d+>}', ...);
```

---

What you think about the release?

**Comment by dominikzogg** [comment]
@fenric sounds good, seems to be very easy to write very thin adapters from my framework to your router

**Comment by dominikzogg** [comment]
@fenric is there a path generation by name with attributes?

**Comment by dominikzogg** [comment]
https://github.com/chubbyphp/chubbyphp-framework/pull/6

**Comment by fenric** [comment]
> [chubbyphp/chubbyphp-framework#6](https://github.com/chubbyphp/chubbyphp-framework/pull/6)

https://github.com/sunrise-php/http-router/issues/27#issuecomment-553382909

**Comment by fenric** [comment]
the version 2.0.0 contains it feature.

examples:

```php
$route->buildPath(array $attributes, bool $strict);
```

or...

```php
$router->getRoute('foo')->buildPath(array $attributes, bool $strict);
```

**Comment by fenric** [comment]
The official release of the new version will be released at the coming days.

**Comment by dominikzogg** [comment]
@fenric thanks, what is the `strict` parameter for?

**Comment by dominikzogg** [comment]
@fenric is there no way to generate url for with not required url parts (/{name}) ?

**Comment by fenric** [comment]
> @fenric thanks, what is the strict parameter for?
> @fenric is there no way to generate url for with not required url parts (/{name}) ?

@dominikzogg in the new version it will be.


```
/foo/{bar}(/{baz<\w+>})/qux
```

```php
// return /foo/bar/qux
$route->buildPath([
    'bar' => 'bar',
]);
```

```php
// return /foo/bar/baz/qux
$route->buildPath([
    'bar' => 'bar',
    'baz' => 'baz',
]);
```

```php
// will be exception:
// [/foo/{bar}(/{baz<\w+>})/qux] missing attribute "bar".
$route->buildPath([
    'baz' => 'baz',
]);
```

```php
// strict mode example
// will be exception:
// [/foo/{bar}(/{baz<\w+>})/qux] "baz" must match "\w+"
$route->buildPath([
    'bar' => 'bar',
    'baz' => '123',
], true);
```

**Comment by fenric** [comment]
@dominikzogg if we are talking about redirects ... in the new version you can do this:

```php
public function handle(ServerRequestInterface $request) : ResponseInterface
{
    // some code...

    return $router->getRoute('foo')->handle($request);
}
```

**Comment by fenric** [comment]
@dominikzogg if we are talking about redirects ... in the new version you can do this:

```php
use Sunrise\Http\Router\RequestHandler\RoutableRequestHandler;

// some code...

public function handle(ServerRequestInterface $request) : ResponseInterface
{
    // some code...

    $handler = new RoutableRequestHandler($router->getRoute('foo'));

    return $handler->handle($request);
}
```

**Comment by dominikzogg** [comment]
`/user/{id<\d+>}(/{name})`

```
self::assertSame(
            'https://user:password@localhost/user/1/sample',
            $router->generateUrl($request, 'user', ['id' => 1, 'name' => 'sample'])
        );
```

what i get is `https://user:password@localhost/user/1(/sample)`

**Comment by dominikzogg** [comment]
and if i don't add the variable `name` i get an expcetion:

1) Chubbyphp\Tests\Framework\Unit\Router\SunriseRouterTest::testGenerateUri
InvalidArgumentException: [/user/{id<\d+>}(/{name})] missing attribute "name".

**Comment by fenric** [comment]
> `/user/{id<\d+>}(/{name})`
> 
> ```
> self::assertSame(
>     'https://user:password@localhost/user/1/sample',
>     $router->generateUrl($request, 'user', ['id' => 1, 'name' => 'sample'])
> );
> ```
> 
> what i get is `https://user:password@localhost/user/1(/sample)`

maybe, I don't understand you... but, parentheses – are system characters. parentheses are always removed from a path when it is build. see:

https://github.com/sunrise-php/http-router/blob/release/v2.0.0/functions/path_build.php#L77

would you like parentheses not to be removed? please, could you describe your problem in more detail?

**Comment by fenric** [comment]
> and if i don't add the variable `name` i get an exception:
> 
> 1. Chubbyphp\Tests\Framework\Unit\Router\SunriseRouterTest::testGenerateUri
>    InvalidArgumentException: [/user/{id<\d+>}(/{name})] missing attribute "name".

yes all is correct. variables (path attributes) can be of 2 types:

1. `not required (optional)` – when the path compiles, and you didn't set a value for such the attribute, then this attribute will be removed with the parentheses.
2. `required` – when the path compiles, and you didn't set a value for such the attribute, an exception will be thrown. because the builder doesn't know what to do.

could you give an idea of what the builder should do when the builder has a required attribute, but there is no value for such an attribute?

**Comment by dominikzogg** [comment]
@fenric other router like the aura ones put the pattern into the url instead of value, but i understand, that your approach is the cleaner onces

**Comment by fenric** [comment]
@dominikzogg 

all are good...

```php
public function testGeneratePathWithOptionalAttributeWithValue(): void
{
    $route = Route::get('/test/{foo}(/bar/{baz}/qux)/quux', 'test', new CallbackRequestHandler(
        function (): void {}
    ));

    $router = new SunriseRouter([$route]);

    self::assertSame(
        '/test/foo/bar/baz/qux/quux?key=value',
        $router->generatePath('test', [
            'foo' => 'foo',
            'baz' => 'baz',
        ], [
            'key' => 'value',
        ])
    );
}

public function testGeneratePathWithOptionalAttributeWithoutValue(): void
{
    $route = Route::get('/test/{foo}(/bar/{baz}/qux)/quux', 'test', new CallbackRequestHandler(
        function (): void {}
    ));

    $router = new SunriseRouter([$route]);

    self::assertSame(
        '/test/foo/quux?key=value',
        $router->generatePath('test', [
            'foo' => 'foo',
        ], [
            'key' => 'value',
        ])
    );
}
```

**Comment by fenric** [comment]
> @fenric other router like the aura ones put the pattern into the url instead of value, but i understand, that your approach is the cleaner onces

but, it isn't correct behaviour... it can provoke broken URIs in your projects. if something goes wrong, the system should immediately "say" so.

**Comment by dominikzogg** [comment]
i agree (this are broken urls), but consistency between the different router implementation is more important atm. and i build apis that are hateoas based so templated url can be helpful

**Comment by fenric** [comment]
I agree with you.  I can substitute the template in non-strict mode.

**Comment by fenric** [comment]
@dominikzogg for example, we have the following path: `/foo(/bar/{baz<\w+>}/qux)/quux`

and, I need to get `/foo/quux` and not `/foo/bar/{baz}/qux/quux`...

what to do then? what do you think about it?

**Comment by fenric** [comment]
@dominikzogg I seem to understand you want:

`/foo(/bar/{baz<\w+>}/qux)/quux` => `/foo/quux`

`/foo/{bar<\w+>}/baz` => /foo/{bar}/baz (if non-strict mode)

yes?

**Comment by dominikzogg** [comment]
@fenric you get what i mean, but please do not change your code, cause my idea is broken, cause the variable also contain the pattern, which depends on router (fastroute got another syntax) implementation, so it can't be used for hateoas, should ask in the first place.

so: for me all is fine, thanks for your help!

**Comment by fenric** [comment]
@dominikzogg I understand. do not change anything :)

**Comment by fenric** [comment]
@dominikzogg I'm sorry, but ... Now, to generate the URI, you must call the method:

```php
$uri = $router->generateUri($name, $attributes);
```

https://github.com/sunrise-php/http-router/blob/release/v2.0.0/src/Router.php#L52

---

`$route->buildPath(...)` – was a bad solution (anti-pattern), very bad... thx!

**Comment by dominikzogg** [comment]
@fenric get that, have the following issue

`public function generateUri(string $name, array $attributes = []) : string`

should be

`public function generateUri(string $name, array $attributes = [], bool $strict = false) : string`

**Comment by dominikzogg** [comment]
and please add more value to the new exception, like attribute name, pattern, given value, for which route as methods on them

**Comment by fenric** [comment]
> and please add more value to the new exception, like attribute name, pattern, given value, for which route as methods on them

completed... and please use the following construction to create a route:

```php
(new RouteFactory)->createRoute(...)
```

the router doesn't contain the `route(...)` method...

**Comment by dominikzogg** [comment]
@fenric thx, adapted the factory part.

i mean to add additional properties to the exceptions which can be read with getters, name, pattern, given value. So i can use those to build framework specific exceptions contain this values.

**Comment by dominikzogg** [comment]
```php
/**
 * MissingAttributeValueException
 */
class MissingAttributeValueException extends RuntimeException implements ExceptionInterface
{
    private $name;

    private $attribute;

    private $value;

    private $expectedPattern;
}
```

as an example

**Comment by fenric** [comment]
well... I don't know... maybe such an implementation would be better:

```php
throw new SomeException(string $message, array $options, ...);
```

```php
throw new InvalidAnnotationSourceException('foo bared blah', [
  'source' => '...',
]);
```

```php
throw new InvalidAnnotationParameterException('foo bared blah', [
  'name' => '...',
]);
```

```php
throw new InvalidPathException('foo bared blah', [
  'path' => '/{foo<\d+>}',
  'position' => 10,
]);
```

```php
throw new InvalidAttributeValueException('foo bared blah...', [
  'path' => '/{foo<\d+>}',
  'attribute' => 'foo',
  'pattern' => '\d+',
]);
```

```php
try {
  // some code...
} catch (ExceptionInterface $e) {
  $e->getOptions(); // use this data...
}
```

etc., etc., etc...

what do you say?

**Comment by dominikzogg** [comment]
@fenric a context array is also ok for me as long key changes are seen as bc's

**Comment by fenric** [comment]
```php
try {
  // some code
} catch (InvalidAttributeValueException $e) {
  $e->getContext(); // see the result...
}
```

```php
try {
  // some code
} catch (MissingAttributeValueException $e) {
  $e->getContext(); // see the result...
}
```

is it ok for you?

**Comment by fenric** [comment]
@dominikzogg excuse me for offtopic... what is **BC**? is it short form for...?

> ... long key changes are seen as bc's

**Comment by dominikzogg** [comment]
@fenric its ok for me thanks. BC (Backward compatibility) so as long those keys (add is ok, but not rename or delete) do not change until lets say version 3 its perfect
