### ISSUE TITLE
MethodNotAllowed is thrown when not needed and vice versa

### ISSUE THREAD

**Issue by rept1d** [sunrise-php/http-router#50]
According to the following code in `Router::match`
```php
$routes = [];
foreach ($this->routes as $route) {
    foreach ($route->getMethods() as $method) {
        $routes[$method][] = $route;
    }
}

$method = $request->getMethod();
if (!isset($routes[$method])) {
    $errmsg = sprintf('The method "%s" is not allowed.', $method);

    throw new MethodNotAllowedException($errmsg, [
        'allowed' => array_keys($routes),
    ]);
}
```
`MethodNotAllowedException` is thrown depending on the list of HTTP Methods from all the routes bound to the Router instead of being based on URL.

This leads to the following cases when it seems like the router doesn't work as intended:

1. On requesting a nonexistent route (path) one can get `MethodNotAllowedException` being throwpn (instead of `RouteNotFoundException`) if the requesting method is not found at any of registered routes.
2. On requesting a registered route (path) using the method that is not supported by that route one can get no exception being thrown if that method is present anywhere else.

You can also check [RFC](https://tools.ietf.org/html/rfc7231#section-6.5.5) to make sure that the current behavior is improper.

**Comment by fenric** [comment]
it's solution for fast matching... [the 1.x version](https://github.com/sunrise-php/http-router/blob/1.x/src/Router.php#L95) contains an other solution...

I can add a new method to the router to switch the match logic (strategy)...

**Comment by fenric** [comment]
thanks for your interest! see version 2.4.
