### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by dominikzogg** [sunrise-php/http-router#60]
I am prepare a PHP 8 compatible release for https://github.com/chubbyphp/chubbyphp-framework-router-sunrise would be cool if you would allow to use your package with php 8.

**Comment by fenric** [comment]
Hi, Dominik! I'm working on it, but the release is expected in early December...

**Comment by fenric** [comment]
Hello! Now Sunrise Router runs on PHP 8. Use version `^2.5`!
