### ISSUE TITLE
Flexible request handler definition for route

### ISSUE THREAD

**Issue by webman** [sunrise-php/http-router#71]
I tried to use this router without annotations/attributes.
All route definition methods require request handler to implement RequestHandlerInterface:
```php
public function get(
    string $name,
    string $path,
    RequestHandlerInterface $requestHandler, // question about this parameter
    array $middlewares = [],
    array $attributes = []
) : RouteInterface {
  ...
}
```

But this is hard to use with invokable actions or controllers. Documentation shows simple example:
```php
$collector = new RouteCollector();
$collector->get('home', '/', new HomeController());
```

Actions and controller constructors can hold dependencies and usage with initiating new action object is not comfortable. It can be solved with DI like so:
```php
$collector->get('test', '/test', $container->get(\App\Action\TestAction::class));
```
but it is not cool too.

I suggest to extend route request handler type to accept callables, path to classes:
```php
$collector->get('test', '/test', \App\Action\Article\UpdateAction::class);
$collector->get('test', '/test', [\App\Controller\ArticleController::class, 'update]);
```

**Comment by fenric** [comment]
I took this feature to work, thanks!

**Comment by fenric** [comment]
https://github.com/sunrise-php/http-router#work-with-psr-11-container

**Comment by fenric** [comment]
@webman since version [2.10.0](https://github.com/sunrise-php/http-router/releases/tag/v2.10.0) the object resolving mechanism has been improved:

Set container, for example for autowire, if you need it:

```php
$collector->setContainer(...);
```

Set callbacks as request handler or middleware:

```php
$collector->get('home', '/', function (ServerRequestInterface $request) : ResponseInterface {
    // some code...
}, [
    function (ServerRequestInterface $request, RequestHandlerInterface $handler) : ResponseInterface {
        // some code...
    },
    function (ServerRequestInterface $request, RequestHandlerInterface $handler) : ResponseInterface {
        // some code...
    },
]);
```

Or set class name as request handler or middleware:

```php
$collector->get('home', '/', App\Http\Controller\HomeController::class, [
    App\Http\Middleware\FooMiddleware::class,
    App\Http\Middleware\BarMiddleware::class,
]);
```

Or set class method as request handler or middleware:

```php
$collector->get('home', '/', [App\Http\Controller\HomeController::class, 'index'], [
    [App\Http\Middleware\FooMiddleware::class, 'foo'],
    [App\Http\Middleware\BarMiddleware::class, 'bar'],
]);
```

Please note that group middlewares needs to be assigned like this:

```php
$collector->group(function ($group) {
    // some code...
}, [
    function (ServerRequestInterface $request, RequestHandlerInterface $handler) : ResponseInterface {
        // some code...
    },
    function (ServerRequestInterface $request, RequestHandlerInterface $handler) : ResponseInterface {
        // some code...
    },
]);
```

```php
$collector->group(function ($group) {
    // some code...
}, [
    App\Http\Middleware\FooMiddleware::class,
    App\Http\Middleware\BarMiddleware::class,
]);
```

```php
$collector->group(function ($group) {
    // some code...
}, [
    [App\Http\Middleware\FooMiddleware::class, 'foo'],
    [App\Http\Middleware\FooMiddleware::class, 'bar'],
]);
```

**Comment by webman** [comment]
@fenric, great, thanks! 

I have one more suggestion. It's be cool if you will log changes in some file like CHANGELOG.md.
E.g. you have renamed methods for adding & unshifting middlewares but there is no information about this changes.

https://github.com/sunrise-php/http-router/pull/74/files#diff-c5ea54501e73ce3376a4c3e8c062215bceb2b8c707dab14c1d54d642e6bdc758R172

**Comment by fenric** [comment]
@webman I can do it... but the add/unshift methods were not deleted:

https://github.com/sunrise-php/http-router/blob/612067e7d19a376bac1636da82f54a9545f702ed/src/RouteCollection.php#L142

https://github.com/sunrise-php/http-router/blob/612067e7d19a376bac1636da82f54a9545f702ed/src/RouteCollection.php#L178

just created new methods:

https://github.com/sunrise-php/http-router/blob/612067e7d19a376bac1636da82f54a9545f702ed/src/RouteCollection.php#L158

https://github.com/sunrise-php/http-router/blob/612067e7d19a376bac1636da82f54a9545f702ed/src/RouteCollection.php#L166

unshift method was marked as deprecated.

i try to maintain backward compatibility...
